%Purpose: To learn how to interpret and use the if and switch structures in
%MATLAB.
%% Part 1 - Questionare
% Describe what the first three executable statements do.
%       The first statement takes a value from the user between 5 and 30.
%       The second value (randVal) picks a random value between 1 and
%       maxVal. The third number is the user's guess as to what number was
%       generated by randVal.
% 
% Explain what is accomplished by lines 5 through 11. 
%       Basically, lines 5 through 11 are trying to figure out if the
%       user's guess was either too high, too low, or correct.
% 
% After line 4, explain which line(s) of code execute(s) and why
%   maxVal = 15, randVal = 11, guessVal = 9
%       lines 5-8 would execute, since the user's guess is too low.
%   maxVal = 23, randVal = 14, guessVal = 17
%       lines 5-6 would execute, since the user's guess is too high.
%   maxVal = 8, randVal = 6, guessVal = 6
%       lines 5-11 would execute, since the user's guess was correct.
% 
% What is the purpose of each ' symbol in line 10?
%       The purpose of it is to indicate that the text is a string. The
%       doublequotes are a replacement for ', so that the phrase |You're|
%       can be said.
% 
clc
clear
maxVal = input('Enter an integer value between 5 and 30.    ');
randVal = randi(maxVal,1,1);
guessVal = input(sprintf('Enter an integer between 0 and %0.0f.     ',...
    maxVal));
if guessVal > randVal
    disp('You guessed too high.')
elseif guessVal < randVal
    disp('You guessed too low.')
else
    disp('Congratulations! You''re a winner!')
end

%% Part 2 - Questionare
% What information is outputted by the strfind function?
%       This function finds the start of a inputted string using a string
%       provided.
% Under what condition will Line 20 be evaluated?
%       It will be evaluated when there are no matches for the single
%       character provided.
% Under what conditions will Line 22 be evaluated?
%       It will be evaluated when there are matches for the single
%       character provided.
% Message1 should be a character array. Give an example of a reasonable
% "value" for Message 1 in this code.
%       'Sorry, that character wasn't found in the provided string.'
% Message2 should be a character array that includes the output of
% length(strfind(inStr, inChar). Give an example of how Message2
% could be defined in this code.
%       'There were matches found.'

Message1 = sprintf('Sorry, that character wasn''t found in the provided string.');
Message2 = sprintf('There were matches found.');
inChar = input('Please enter a single character.    ','s');
inStr = input('Please enter a character string.     ','s');
if length(strfind(inStr, inChar)) == 0
    disp(Message1)
else
    disp(Message2)
end

%% Problem 2.5
% Try rewriting the code using switch/case/otherwise structures instead of
% the if/else structure. 

Message1 = sprintf('Sorry, that character wasn''t found in the provided string.');
Message2 = sprintf('There were matches found.');
inChar = input('Please enter a single character.    ','s');
inStr = input('Please enter a character string.     ','s');
finalChar = length(strfind(inStr, inChar))

switch finalChar
    case 0
        disp(Message1)
    case finalChar > 0
        disp(Message2)
    otherwise
        disp('You cannot follow directions!')
end

%% Problem 3
% What is the char function doing in Line 28?
%       It is creating an array of strings.
% Can you determine the dimensions of the variable promptList based on the
% input arguments for the char function?
%       I would say it would be a 4x1.
% What does line 29 do?
%       Displays the list.
% What does line 30 do?
%       Asks the user to pick one of the commands from the list.
% What does line 31 do?
%       This displays a \n to move the code up in the command window.
% Explain the relationship between lines 33, 34, 36, 38, 40, and 42.
%       Basically, it checks to see which number the user gave, and returns
%       the resulting function relevant to that number. If the number does
%       not match one of the function holders, then it will go immediately
%       to the otherwise statement.

promptList = char('1: eye(5)', '2: diag([1,2,3])', '3: rand(4)', '4: randi(20,4)');
disp(promptList)
selectVal = input('Select the number for one of the commands listed to see the output.  ');
disp(newline)

switch selectVal
    case 1
        disp(eye(5))
    case 2
        disp(diag([1,2,3]))
    case 3
        disp(rand(4))
    case 4
        disp(randi(20,4))
    otherwise
        disp('You did not choose one of the specified values.')
end

%% Problem 4 - Questionare
% What is the char function doing in Line 51? 
%       It is creating a string with a list of colors.
% Can you determine the dimensions of the variable colorList based on the
% input arguments for the char function?
%       Yes, the dimensions are 1x7.
% What is the purpose of the lower function used in Line 55? How would
% removing the lower function impact the way the script runs?
%       Basically, the lower function takes capitalization out of the
%       question when comparing two strings, which makes the program a lot
%       easier to read, understand, use, and compile.

disp('Type in the name of a color from the list below to see the MATLAB color triplet.')
disp(newline)
colorList = char('maroon', 'olive', 'purple', 'teal', 'navy', 'sienna', 'hot pink');
disp(colorList)
colorSelect = input(sprintf('\nSelected color:    '),'s');

switch lower(colorSelect)
    case 'maroon'
        colorTrip = [128/255 0 0];
    case 'olive'
        colorTrip = [128/255 128/255 0];
    case 'purple'
        colorTrip = [128/255 0 128/255];
    case 'teal'
        colorTrip = [0 128/255 128/255];
    case 'navy'
        colorTrip = [0 0 128/255];
    case 'sienna'
        colorTrip = [160/255 82/255 45/255];
    case 'hot pink'
        colorTrip = [1 105/255 180/255];
    otherwise
end
disp(sprintf('\nThe color triplet for %s is\n',lower(colorSelect)))
disp(colorTrip)

